Repository guytepper/1km.co.il, pull requests merged in 2020-10, with the labels that each got.

#48 Save user coordinates on local storage and reuse them if possible
  src/App.js
  src/localStorage.js
Labels: reviewed

#43 Fix protest list bug
  src/App.js
  src/components/Map/Map.js
  src/components/Modal/Modal.js
Labels: reviewed

#73 Enables protest page link
  src/components/ProtestCard/ProtestCard.js
Labels: urgent

#71 Adds social share buttons to protest page
  package.json
  src/views/ProtestPage.js
  src/views/ProtestPageTexts.json
  yarn.lock
Labels: reviewed

#72 Users, Sign-In & Leader request flow
  package.json
  src/App.js
  src/api/index.js
  src/views/Admin.js
  src/views/LeaderRequest.js
  src/views/LeaderRequestSubmitted.js
  src/views/Profile.js
  src/views/SignUp.js
  src/views/index.js
  yarn.lock
Labels: urgent

#37 Added basic MDX functionality
  package.json
  src/App.js
  src/components/Footer/Footer.js
  src/components/Post/Post.js
  src/components/Post/PostWrapper.js
  src/components/Post/index.js
  src/components/index.js
  src/views/FourOhFour.js
  src/views/PostView.js
  src/views/Posts/ProjectUpdates/one.js
  src/views/Posts/four-oh-four.js
  src/views/Posts/index.js
  src/views/Posts/legal-notice.js
  src/views/Posts/project-support.js
  src/views/ProjectSupportPage/index.js
  src/views/ProjectUpdates/index.js
  src/views/index.js
  yarn.lock
Labels: reviewed, urgent

#118 Fix: Protected route not redirecting to signup page correctly
  src/components/ProtectedRoute/ProtectedRoute.js
Labels: bug, ready for review

#144 Update project support page
  src/components/Post/PostWrapper.js
  src/views/Posts/project-support.js
Labels: ready for review

#136 Modal sizing
  src/components/Modal/Modal.js
Labels: in progress

#64 Show protest card on marker popup
  package.json
  src/components/Map/Map.js
  src/index.css
  yarn.lock
Labels: in progress
